version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss:10.4.10
    user: "472"
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.200,rw,nfsvers=4"
      device: ":/storage/dockerswarm/grafana/data"
  grafana_provisioning:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.200,rw,nfsvers=4"
      device: ":/storage/dockerswarm/grafana/provisioning"
