---
- name: Zabbix API Version
  vars:
    ansible_zabbix_auth_key: <APIKEY>
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: '/'  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
    ansible_host: 192.168.0.11
  delegate_to: g7
  community.zabbix.zabbix_host:
    host_name: "{{ ansible_hostname }}"
    description: Ansible
    host_groups: homelab
    tls_psk_identity: "{{ ansible_hostname }}"
    tls_accept: 2 # Possible values, 1 (no encryption), 2 (PSK), 4 (certificate).
    tls_connect: 2 # Possible values, 1 (no encryption), 2 (PSK), 4 (certificate).
    tls_psk: "<PSKKEY>"
    status: enabled
    state: present
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: "{{ ansible_hostname }}"
        port: "{{ agent_zabbix_port }}"
    proxy: zabbixproxy