---
- name: Install packages
  ansible.builtin.apt:
    name: 
      - binutils
    state: present
    update_cache: yes

- name: Set fact ubuntu like package
  ansible.builtin.set_fact: 
    url_custom_ubu: "https://repo.zabbix.com/zabbix/{{ zabbix_major_version }}/ubuntu/pool/main/z/zabbix/zabbix-agent2_{{ zabbix_major_version }}.{{ zabbix_minor_version }}-1%2Bubuntu{{ ansible_distribution_version }}_amd64.deb"

- name: Download temp file
  ansible.builtin.get_url:
    url: "{{ url_custom_ubu }}"
    dest: "{{ temp_dir }}"

- name: Extract .deb ubuntu
  ansible.builtin.shell: cd {{ temp_dir }};/usr/bin/ar x zabbix-agent2_{{ zabbix_major_version }}.{{ zabbix_minor_version }}-1%2Bubuntu{{ ansible_distribution_version }}_amd64.deb;tar xvf data.tar.xz;

