NUM_NODES = 3
IP_BASE = "192.168.0."
SSH_PUBLIC_KEY_PATH = File.expand_path("~/.ssh/id_rsa.pub")

Vagrant.configure("2") do |config|
  (1..NUM_NODES).each do |i|
    hostname = "node%02d" % i
    ip = IP_BASE + (90 + i).to_s

    config.vm.define hostname do |nodeconfig|
      nodeconfig.vm.box = "rockylinux/9"
      nodeconfig.vm.hostname = hostname
      nodeconfig.vm.synced_folder ".", "/vagrant", disabled: true
      nodeconfig.ssh.username = 'vagrant'
      nodeconfig.ssh.insert_key = false

      nodeconfig.vm.network "public_network", bridge: ["wlp0s20f3"], ip: ip

      nodeconfig.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end

      nodeconfig.vm.provision "file", source: SSH_PUBLIC_KEY_PATH, destination: "/home/vagrant/.ssh/id_rsa.pub"

      nodeconfig.vm.provision "shell", inline: <<-SHELL
        mkdir -p /home/vagrant/.ssh
        cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        chmod 600 /home/vagrant/.ssh/authorized_keys
        chown -R vagrant:vagrant /home/vagrant/.ssh
      SHELL
    end
  end
end
