global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'your.email@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:25'
    auth_username: 'username'
    auth_password: 'password'