version: '3.8'

services:
 grafana:
  image: grafana/grafana-oss:11.2.2-security-01
  container_name: grafana
  user: "472"
  restart: unless-stopped
  ports:
    - '3000:3000'
  volumes:
      - grafana_data:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning/
  environment:
    GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
    GF_SECURITY_ADMIN_USER: admin
    GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw
      device: ":/path/to/nfs/share"

  grafana_provisioning:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw
      device: ":/path/to/nfs/share"
